apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-index
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="pt-br">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Kubernetes Test</title>

        <style>
            body {
                font-family: Arial, Helvetica, sans-serif;
                background: #f1f1f1;
                padding: 50px;
                text-align: center;
            }

            h1 {
                color: #222;
                margin-bottom: 40px; /* Mais espaÃ§o entre os textos */
            }

            .mensagem {
                margin-top: 40px;
                padding: 25px;
                font-size: 24px;
                font-weight: bold;
                color: #333;

                /* Caixa com borda bonita */
                border: 3px solid #6a00ff;
                border-radius: 15px;
                background: white;

                /* Sombra para destacar */
                box-shadow: 0 5px 15px rgba(0,0,0,0.15);

                /* Largura suave */
                display: inline-block;
            }
        </style>
    </head>
    <body>
        <h1>Deploy AutomÃ¡tico do HTML via Kubernetes (K3s + Github Actions)</h1>
        <h1>Funcionando via NGINX + Kubernetes na VM Azure! ðŸš€</h1>

        <div class="mensagem">
            Vote JosÃ© Guilherme para melhor professor ðŸŽ“âœ¨
        </div>
    </body>
    </html>


